### ISSUE TITLE
feature request: integer mode

### ISSUE THREAD

**Issue by cowens** [gregsexton/VimCalc#1]
I would like to be able to use an `:int` directive an have all calculations use integer arithmetic rather than floating point.  Obviously, this would require a `:float` directive to return to floating point arithmetic.

**Comment by gregsexton** [comment]
This shouldn't be too hard to do. I'm curious, do you want an 'integer mode' just so that, for example, the '.0' from 'ans = 4.0' gets dropped? It may be nicer to test the result of an expression for an integer and adjust the display output appropriately. Internally it would still be represented as a float. Is there something grander I've missed?

I also intend to replace the internal floats with arbitrary precision arithmetic at some point in the future. Would you want to be able to limit the precision to floats then too?

**Comment by cowens** [comment]
No, I really want `1/2*5` to be `0` (rather than `2.5`).  It would be analogous to saying floor(floor(1/2)*5).

**Comment by gregsexton** [comment]
:int and :float directives have been added with commit d4fbd460. Download the latest source and let me know if it works for you.

```
> 1/2*5
ans = 2.5
> :int
CHANGED OUTPUT PRECISION TO INTEGER.
> 1/2*5
ans = 0
```
